using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Threading;
using Forms = System.Windows.Forms;
using PomodoroClock.Core;
using PomodoroClock.Infrastructure;

namespace PomodoroClock.App;

public partial class MainWindow : Window
{
    private readonly LocalFileLogger _log; private readonly SqliteWorkItemRepository _tasks; private readonly SqliteSessionRepository _sessions; private readonly DispatcherTimer _timer; private PomodoroTimer _pomodoro = null!; private TimerSettings _settings = new(); private Forms.NotifyIcon _tray = null!; private bool _allowExit; private bool _handlingCompletion; private bool _selectionEventsReady;
    public ObservableCollection<WorkItem> Items { get; } = new();
    public MainWindow(SqliteDatabase db, LocalFileLogger log)
    {
        InitializeComponent(); _log=log; _tasks=new(db); _sessions=new(db); _timer=new(){Interval=TimeSpan.FromMilliseconds(300)}; _timer.Tick += (_,_) => RefreshTimer(); Loaded += async (_,_) => await InitializeAsync();
        var trayIcon=System.Drawing.Icon.ExtractAssociatedIcon(System.Diagnostics.Process.GetCurrentProcess().MainModule?.FileName??string.Empty)??System.Drawing.SystemIcons.Application; _tray=new Forms.NotifyIcon{Visible=true,Text="番茄时钟",Icon=trayIcon}; var menu=new Forms.ContextMenuStrip(); menu.Items.Add("显示主窗口",null,(_,_)=>ShowWindow()); menu.Items.Add("退出程序",null,(_,_)=>ExitApplication()); _tray.ContextMenuStrip=menu; _tray.DoubleClick += (_,_)=>ShowWindow();
        // Default selections in XAML raise SelectionChanged while InitializeComponent is
        // still building the visual tree. Enable data-loading handlers only after the
        // window and all of its dependencies have been constructed.
        _selectionEventsReady=true;
    }
    private async Task InitializeAsync(){try{_settings=await _sessions.GetTimerSettingsAsync();_pomodoro=new PomodoroTimer(settings:_settings,completedRounds:await _sessions.GetCompletedRoundsAsync());ApplySettings();RefreshTimer();await ReloadTasksAsync();await ReloadStatsAsync();}catch(Exception ex){_log.Error(ex,"初始化");MessageBox.Show("应用初始化失败，请检查数据目录权限。","番茄时钟",MessageBoxButton.OK,MessageBoxImage.Error);}}
    private void RefreshTimer(){if(_pomodoro is null)return;var s=_pomodoro.Tick();PhaseText.Text=s.Phase switch{TimerPhase.Focus=>"专注",TimerPhase.ShortBreak=>"短休息",_=>"长休息"};RoundsText.Text=$"本周期已完成 {s.CompletedRounds} 轮";var sec=Math.Max(0,(int)Math.Ceiling(s.Remaining.TotalSeconds));TimeText.Text=$"{sec/60:00}:{sec%60:00}";StartButton.Content=s.Status==TimerStatus.AwaitingSettlement?"待结算":s.Status==TimerStatus.Running?"进行中":"开始";StartButton.IsEnabled=s.Status==TimerStatus.Ready;if(s.Status==TimerStatus.Running)_timer.Start();else _timer.Stop();_tray.Text=$"番茄时钟 · {PhaseText.Text} {TimeText.Text}";if(s.Status==TimerStatus.AwaitingSettlement&&!_handlingCompletion)_=HandleCompletionAsync(s);}
    private void StartClick(object s,RoutedEventArgs e){_pomodoro.Start();RefreshTimer();}
    private void CancelClick(object s,RoutedEventArgs e){_pomodoro.Cancel();RefreshTimer();}
    private void ResetClick(object s,RoutedEventArgs e){_pomodoro.Cancel();RefreshTimer();}
    private void SkipClick(object s,RoutedEventArgs e){if(_pomodoro.SkipBreak())RefreshTimer();}
    private async Task HandleCompletionAsync(TimerSnapshot snap){_handlingCompletion=true;try{var start=snap.StartedAt??DateTimeOffset.UtcNow;var end=snap.TargetEnd??DateTimeOffset.UtcNow;_tray.ShowBalloonTip(5000,"专注完成","本轮专注已完成，请记录工作内容。",Forms.ToolTipIcon.Info);System.Media.SystemSounds.Exclamation.Play();var selected=await ShowSettlementAsync();var longBreak=snap.CompletedRounds+1>=_settings.RoundsBeforeLongBreak;await _sessions.SaveSettlementAsync(new(Guid.NewGuid(),start,end,(int)Math.Max(1,(end-start).TotalSeconds)),selected.ids,selected.newTitle,snap.CompletedRounds+1,longBreak);_pomodoro.CompleteFocusAndSetNextPhase(longBreak);await ReloadTasksAsync();await ReloadStatsAsync();}catch(Exception ex){_log.Error(ex,"保存专注记录");MessageBox.Show("本轮保存失败，数据库未被修改，请稍后重试。","番茄时钟",MessageBoxButton.OK,MessageBoxImage.Error);}finally{_handlingCompletion=false;RefreshTimer();}}
    private async Task<(IReadOnlyCollection<Guid> ids,string? newTitle)> ShowSettlementAsync(){var items=await _tasks.GetAsync();var win=new Window{Title="本轮工作记录",Owner=this,Width=480,Height=540,MinWidth=380,MinHeight=420,WindowStartupLocation=WindowStartupLocation.CenterOwner};var root=new Grid{Margin=new Thickness(24)};root.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});root.RowDefinitions.Add(new RowDefinition{Height=new GridLength(1,GridUnitType.Star)});root.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});root.Children.Add(new TextBlock{Text="选择本轮参与的工作事项",FontSize=18,FontWeight=FontWeights.SemiBold,Margin=new Thickness(0,0,0,12)});var list=new StackPanel();var checks=new List<(Guid,CheckBox)>();foreach(var i in items){var cb=new CheckBox{Content=i.Title,Margin=new Thickness(0,5,0,5)};checks.Add((i.Id,cb));list.Children.Add(cb);}var scroll=new ScrollViewer{Content=list,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};Grid.SetRow(scroll,1);root.Children.Add(scroll);var footer=new StackPanel{Margin=new Thickness(0,18,0,0)};footer.Children.Add(new TextBlock{Text="新建工作内容（可选）",Margin=new Thickness(0,0,0,6)});var input=new TextBox();footer.Children.Add(input);var save=new Button{Content="保存本轮",Style=(Style)FindResource("PrimaryButtonStyle"),MinWidth=112,Margin=new Thickness(0,16,0,0),HorizontalAlignment=HorizontalAlignment.Right};footer.Children.Add(save);Grid.SetRow(footer,2);root.Children.Add(footer);(IReadOnlyCollection<Guid> ids,string? title) result=(Array.Empty<Guid>(),null);save.Click+=(_,_)=>{result=(checks.Where(x=>x.Item2.IsChecked==true).Select(x=>x.Item1).ToArray(),string.IsNullOrWhiteSpace(input.Text)?null:input.Text.Trim());win.DialogResult=true;};win.Content=root;win.ShowDialog();return result;}
    private async void SaveSettingsClick(object s,RoutedEventArgs e){try{var v=new TimerSettings(int.Parse(FocusBox.Text),int.Parse(ShortBox.Text),int.Parse(LongBox.Text),int.Parse(RoundsBox.Text));v.Validate();await _sessions.SaveTimerSettingsAsync(v);_settings=v;_pomodoro.UpdateSettings(v);SettingsMessage.Text="设置已保存，将从下一阶段生效。";}catch{SettingsMessage.Text="请输入有效数字：专注 1-120，短休息 1-60，长休息 1-120，间隔 1-12。";}}
    private void ApplySettings(){FocusBox.Text=_settings.FocusMinutes.ToString();ShortBox.Text=_settings.ShortBreakMinutes.ToString();LongBox.Text=_settings.LongBreakMinutes.ToString();RoundsBox.Text=_settings.RoundsBeforeLongBreak.ToString();}
    private async void NewTaskClick(object s,RoutedEventArgs e){var w=new Window{Title="新建事项",Owner=this,Width=400,Height=220,MinWidth=340,WindowStartupLocation=WindowStartupLocation.CenterOwner};var p=new StackPanel{Margin=new Thickness(24)};p.Children.Add(new TextBlock{Text="事项名称",Margin=new Thickness(0,0,0,6)});var input=new TextBox{MaxLength=120};p.Children.Add(input);var b=new Button{Content="保存事项",Style=(Style)FindResource("PrimaryButtonStyle"),MinWidth=112,Margin=new Thickness(0,16,0,0),HorizontalAlignment=HorizontalAlignment.Right};p.Children.Add(b);b.Click+=(_,_)=>{if(!string.IsNullOrWhiteSpace(input.Text))w.DialogResult=true;};w.Content=p;if(w.ShowDialog()==true){await _tasks.SaveAsync(new(Guid.NewGuid(),input.Text.Trim(),"",WorkItemStatus.InProgress,WorkItemPriority.Normal,DateTimeOffset.UtcNow,null,0));await ReloadTasksAsync();}}
    private async void ReloadTasks(object s,SelectionChangedEventArgs e){if(!_selectionEventsReady)return;await ReloadTasksAsync();}
    private async Task ReloadTasksAsync(){Items.Clear();var all=await _tasks.GetAsync();var filtered=StatusFilter.SelectedIndex switch{1=>all.Where(x=>x.Status==WorkItemStatus.InProgress),2=>all.Where(x=>x.Status==WorkItemStatus.Completed),_=>all};foreach(var x in filtered)Items.Add(x);TasksList.ItemsSource=Items;}
    private async Task ReloadStatsAsync(){var d=DateOnly.FromDateTime(DateTime.Now);var summary=await _sessions.GetAsync(d,d);TodayPomodoros.Text=summary.Pomodoros.ToString();TodayMinutes.Text=$"{summary.FocusMinutes} 分钟";SessionsList.ItemsSource=summary.Sessions;}
    private void NavTimer(object s,RoutedEventArgs e){Pages.SelectedIndex=0;SetPage("今天 · 专注模式","开始一轮专注");}private void NavTasks(object s,RoutedEventArgs e){Pages.SelectedIndex=1;SetPage("工作台 · 事项","把想法拆成下一步行动");}private void NavStats(object s,RoutedEventArgs e){Pages.SelectedIndex=2;SetPage("回顾 · 今日","每一次完整专注，都会留下清晰的轨迹");}private void NavSettings(object s,RoutedEventArgs e){Pages.SelectedIndex=3;SetPage("偏好设置","计时节奏和应用行为");}private void SetPage(string eyebrow,string title){PageEyebrow.Text=eyebrow;PageTitle.Text=title;}private async void Pages_SelectionChanged(object s,SelectionChangedEventArgs e){if(!_selectionEventsReady)return;if(Pages.SelectedIndex==1)await ReloadTasksAsync();if(Pages.SelectedIndex==2)await ReloadStatsAsync();}
    private void ShowWindow(){Show();WindowState=WindowState.Normal;Activate();} private void ExitApplication(){_allowExit=true;Close();}
    private void Window_Closing(object? sender,System.ComponentModel.CancelEventArgs e){if(!_allowExit){e.Cancel=true;Hide();return;}if(_pomodoro?.Snapshot.Status==TimerStatus.Running&&MessageBox.Show("专注正在进行，退出后本轮不会计入统计。确定退出吗？","番茄时钟",MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes){e.Cancel=true;return;}_tray.Visible=false;_timer.Stop();}
}
