<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <RootNamespace>PomodoroClock.App</RootNamespace>
    <AssemblyName>番茄时钟</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PomodoroClock.Core\PomodoroClock.Core.csproj" />
    <ProjectReference Include="..\PomodoroClock.Infrastructure\PomodoroClock.Infrastructure.csproj" />
  </ItemGroup>

</Project>
